name: GH CLI Test Workflow
on:
  workflow_dispatch:

permissions:
    id-token: write
    contents: read

jobs:
  test_gh_cli:
    name: Determine whether gh cli is installed
    runs-on: ubuntu-latest
    steps:
     - name: "which gh"
      run: "which gh"
